name: Scala CI
on:
 push:
   branches: [ main, develop]
 pull_request:
   branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
   steps:
   - uses: actions/checkout@v3
   - name: Set up JDK 19
     uses: actions/setup-java@v3
     with:
       java-version: '19'
       distribution: 'adopt'
       cache: 'sbt'
   - name: Run tests
     run: sbt test
   - name: Download and install JavaFX
     run: |
       wget https://gluonhq.com/download/javafx-14.0.2-sdk-linux/
       unzip javafx-sdk-14.0.2.zip -d $HOME
       echo "export PATH=$PATH:$HOME/javafx-sdk-14.0.2/lib" >> $HOME/.bashrc
       shell: bash
   - name: Assembly | Build JAR
     run: sbt clean assembly
     env:
       JAVA_OPTS: "-Djavafx.verbose=true" 
   - name: Upload JAR artifact
     uses: actions/upload-artifact@v4
     with:
       name: backgammon
       path: target/scala-3.3.1/backgammon.jar
 run_tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Build Project and export Coverage
       env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       run: |
         export CI_BRANCH="${GITHUB_REF#refs/heads/}"
         sbt clean coverage test coverageReport coveralls
